#!/bin/sh
serverCommaList=${1?need comma delimitted list of servers}
serverDelayCommaList=${2:-} #comma list of integers for a delay between each puppet run
loginAs=${2:-}

serverArray=(${serverCommaList//,/ })
if [ $serverDelayCommaList ]; then
        serverDelayArray=(${serverDelayCommaList//,/ })
fi

if [ ${#serverArray[@]} != ${#serverDelayCommaList[@]} ]; then
        echo Array mismatch on serverArray to serverDelayCommaList, exiting!!!
        exit 1
fi

ssh_func(){
        machine=$1
        user=$2
        delay=$3

        if [ "$user" ]; then
                echo Attempting to ssh into "$machine" as "$user" !
                ssh -t -t "$user"@"$machine" 'sudo puppet agent -t'
        else
                echo Attempting to ssh into "$machine" !
                # -t -t forces psuedo terminal even whent here is no stdin
                #http://stackoverflow.com/questions/7114990/pseudo-terminal-will-not-be-allocated-because-stdin-is-not-a-terminal
                #required for jenkins
                ssh -t -t "$machine" 'sudo puppet agent -t'
        fi
        if [ $delay ]; then
                sleep $delay
        fi
}

for i in "${!serverArray[@]}";
do
        ssh_func ${serverArray["$i"]} "$loginAs" ${serverDelayArray["$i"]}
done
exit 0