#!/bin/sh
serverCommaList=${1?need comma delimitted list of servers}
loginAs=${2:-}

serverArray=(${serverCommaList//,/ })

ssh_func(){
        machine=$1
        user=$2

        if [ "$user" ]; then
                echo Attempting to ssh into "$machine" as "$user" !
                ssh -t "$user"@"$machine" 'sudo puppet agent -t'
        else
                echo Attempting to ssh into "$machine" !
                ssh -t "$machine" 'sudo puppet agent -t'
        fi
}

for i in "${!serverArray[@]}";
do
        ssh_func ${serverArray["$i"]} "$loginAs"
done
exit 0