#!/bin/sh
#curl get result and compare it to expected
serviceUrl=${1?need a url to get from}
appName=${2?need application name}
delayMilli=${3?missing expected delay in milliseconds} #if parameter contains spaces they should be enclosed in "" or ''

curl_command(){
  url=$1
  app=$2
  delay=$3

  echo '/////////////////--Begin--Validate--Endpoint/////////'

  echo 'curl '"$url"'/apps/validate/'"$app"'/'"$delay"
  
  curl "$url"'/apps/validate/'"$app"'/'"$delay"

  echo '/////////////////END--Validate--Enpoint////////////'
}
$(curl_command "$serviceUrl" "$appName" "$delayMilli")