#!/bin/sh
#works with gnu sed
moduleName=${1?need module name}
pathToModuleName=${2?need module name path}
OSX=${3:-}
pathToRunInSSH_SH=${4:-'./'}
pathAndmoduleName="$pathToModuleName""$moduleName"


newSshModuleName=$moduleName'.sh'
cp "$pathToRunInSSH_SH"run_in_ssh.sh  "$newSshModuleName"


sshArgs="$pathAndmoduleName"'/ssh_args.sh'
sshExecutionContent="$pathAndmoduleName"'/to_execute.sh'
generatedScriptArgs="$pathAndmoduleName"'/top_args.sh'

sed -i '/REPLACE_WITH_TOP_ARGS/{
	s/REPLACE_WITH_TOP_ARGS//g
	r '"$generatedScriptArgs"'
}' "$newSshModuleName"

sed -i '/REPLACE_WITH_ARGS/{
	s/REPLACE_WITH_ARGS//g
	r '"$sshArgs"'
}' "$newSshModuleName"

sed -i 's/SSHCMD /ssh /;N;G;s/\n//g' "$newSshModuleName"

sed -i '/REPLACE_WITH_EXEC_CONTENT/{
	s/REPLACE_WITH_EXEC_CONTENT//
	r '"$sshExecutionContent"'
	N
}' "$newSshModuleName"

chmod 755 "$newSshModuleName"
mv "$newSshModuleName" ./createdFromTemplate